# Generated by Django 4.2.10 on 2024-03-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openningtime',
            name='weekday',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=40),
        ),
    ]
