# Generated by Django 4.2.10 on 2024-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='es', max_length=7),
        ),
    ]
