# Generated by Django 4.2.10 on 2024-06-24 16:06

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=appt_calendar_app.models.blog_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='post_header_image',
            field=models.ImageField(blank=True, null=True, upload_to=appt_calendar_app.models.post_header_directory_path),
        ),
    ]
