# Generated by Django 4.2.10 on 2024-05-29 05:15

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountui',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=appt_calendar_app.models.account_directory_path),
        ),
    ]
