# Generated by Django 4.2.10 on 2024-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0002_alter_openningtime_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_slot_duration',
            field=models.IntegerField(default=30),
        ),
    ]
