# Generated by Django 4.2.10 on 2024-05-30 07:45

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0002_alter_accountui_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventui',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=appt_calendar_app.models.event_directory_path),
        ),
    ]
