# Generated by Django 4.2.10 on 2024-06-25 14:37

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0003_alter_blog_blog_image_alter_post_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
