# Generated by Django 4.2.10 on 2024-05-30 07:58

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0003_alter_eventui_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=appt_calendar_app.models.custom_user_directory_path),
        ),
    ]
