# Generated by Django 4.2.10 on 2024-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0003_account_time_slot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
