# Generated by Django 4.2.10 on 2024-05-30 08:13

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessappearance',
            name='appointment_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=appt_calendar_app.models.web_directory_path),
        ),
    ]
