# Generated by Django 4.2.10 on 2024-05-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0005_alter_businessappearance_appointment_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_page_options', to='appt_calendar_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('event_page_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='appt_calendar_app.eventpageoptions')),
            ],
        ),
        migrations.CreateModel(
            name='EventPageAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('single_line', 'Single Line'), ('multi_line', 'Multiple Lines'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('dropdown', 'Dropdown')], max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='appt_calendar_app.eventpagequestion')),
            ],
        ),
    ]
