# Generated by Django 4.2.10 on 2024-05-31 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0006_eventpageoptions_eventpagequestion_eventpageanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appt_calendar_app.appointment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appt_calendar_app.eventpagequestion')),
            ],
        ),
    ]
