# Generated by Django 4.2.10 on 2024-06-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0007_appointmentquestionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentquestionresponse',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='appt_calendar_app.appointment'),
        ),
    ]
