# Generated by Django 4.2.10 on 2024-04-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0008_appointment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='active',
        ),
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
