# Generated by Django 4.2.10 on 2024-04-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0009_remove_appointment_active_event_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui', to='appt_calendar_app.event')),
            ],
        ),
    ]
