# Generated by Django 4.2.10 on 2024-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0010_eventui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventui',
            name='image',
            field=models.ImageField(blank=True, default='events/placeholder.jpg', null=True, upload_to='events/'),
        ),
    ]
