# Generated by Django 4.2.10 on 2024-06-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0010_usersocialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialmedia',
            old_name='linkedin',
            new_name='tiktok',
        ),
    ]
