# Generated by Django 4.2.10 on 2024-04-27 09:49

import appt_calendar_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0011_alter_eventui_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventui',
            name='image',
            field=models.ImageField(blank=True, default='events/placeholder.jpg', null=True, upload_to=appt_calendar_app.models.event_directory_path),
        ),
        migrations.CreateModel(
            name='AccountUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('header_image', models.ImageField(blank=True, default='businesses/placeholder.jpg', null=True, upload_to=appt_calendar_app.models.account_directory_path)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui', to='appt_calendar_app.account')),
            ],
        ),
    ]
