# Generated by Django 4.2.10 on 2024-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0012_alter_eventui_image_accountui'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountui',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
