# Generated by Django 4.2.10 on 2024-04-29 14:41

import appt_calendar_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0013_accountui_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.CreateModel(
            name='BusinessEventImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='events/placeholder.jpg', null=True, upload_to=appt_calendar_app.models.event_uploads_directory_path)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appt_calendar_app.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appt_calendar_app.event')),
            ],
        ),
    ]
