# Generated by Django 4.2.10 on 2024-04-30 12:31

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0014_remove_event_location_businesseventimageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='user_profile/placeholder.jpg', null=True, upload_to=appt_calendar_app.models.custom_user_directory_path),
        ),
    ]
