# Generated by Django 4.2.10 on 2024-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0015_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='presentation',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
