# Generated by Django 4.2.10 on 2024-04-30 16:11

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0016_customuser_experience_customuser_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='user_profiles/placeholder.jpg', null=True, upload_to=appt_calendar_app.models.custom_user_directory_path),
        ),
    ]
