# Generated by Django 4.2.10 on 2024-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0017_event_price_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presentation',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
