# Generated by Django 4.2.10 on 2024-05-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0018_event_presentation_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openningtime',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='appt_calendar_app.account'),
        ),
    ]
