# Generated by Django 4.2.10 on 2024-05-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0020_address_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesseventimageupload',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='appt_calendar_app.account'),
        ),
        migrations.AlterField(
            model_name='businesseventimageupload',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='appt_calendar_app.event'),
        ),
    ]
