# Generated by Django 4.2.10 on 2024-05-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0021_alter_businesseventimageupload_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bar_color', models.CharField(default='#FFFFFF', help_text='Stores the color of the header bar as a hex code.', max_length=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appt_calendar_app.account')),
            ],
        ),
    ]
