# Generated by Django 4.2.10 on 2024-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0025_businessappearance_container_wide_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessappearance',
            name='container_wide_color',
            field=models.CharField(default='#FFFFFF', help_text='Stores the color of the background as a hex code.', max_length=7),
        ),
    ]
