# Generated by Django 4.2.10 on 2024-05-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0026_alter_businessappearance_container_wide_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessappearance',
            old_name='container_wide_color',
            new_name='background_color',
        ),
        migrations.AddField(
            model_name='businessappearance',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Stores the color of the text as a hex code.', max_length=7),
        ),
    ]
