# Generated by Django 4.2.10 on 2024-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0027_rename_container_wide_color_businessappearance_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='section_header_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Stores the color of the sections header text as a hex code.', max_length=7),
        ),
    ]
