# Generated by Django 4.2.10 on 2024-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0028_businessappearance_section_header_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='service_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Stores the color of the service background color as a hex code.', max_length=7),
        ),
        migrations.AddField(
            model_name='businessappearance',
            name='worker_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Stores the color of the service background color as a hex code.', max_length=7),
        ),
    ]
