# Generated by Django 4.2.10 on 2024-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0029_businessappearance_service_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='hero_image_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Font colors for text on presentation image', max_length=7),
        ),
    ]
