# Generated by Django 4.2.10 on 2024-05-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0030_businessappearance_hero_image_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='header_bar_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Font color for text on header bar', max_length=7),
        ),
    ]
