# Generated by Django 4.2.10 on 2024-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0031_businessappearance_header_bar_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='main_manu_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Font colors for text on presentation image', max_length=7),
        ),
    ]
