# Generated by Django 4.2.10 on 2024-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0032_businessappearance_main_manu_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='main_menu_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Font colors for main menu links', max_length=7),
        ),
        migrations.AddField(
            model_name='businessappearance',
            name='main_menu_font_hover_color',
            field=models.CharField(default='#FFFFFF', help_text='Font colors for main menu links hover', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='main_manu_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color for main menu', max_length=7),
        ),
    ]
