# Generated by Django 4.2.10 on 2024-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0033_businessappearance_main_menu_font_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='buger_menu_lines_color',
            field=models.CharField(default='#FFFFFF', help_text='Burger menu line colors', max_length=7),
        ),
        migrations.AddField(
            model_name='businessappearance',
            name='burger_button_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color for burger main menu', max_length=7),
        ),
    ]
