# Generated by Django 4.2.10 on 2024-05-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0034_businessappearance_buger_menu_lines_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessappearance',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='Color of the website background.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='header_bar_color',
            field=models.CharField(default='#FFFFFF', help_text='Color of the header bar.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='header_bar_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Font color for text on header bar.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='hero_image_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Colors for text on main website image', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='main_menu_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Font color for main menu links', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='section_header_font_color',
            field=models.CharField(default='#FFFFFF', help_text='Color of the sections header text.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='service_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Color of the service background card.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Color of the text on the website.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='worker_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Color of the worker background card.', max_length=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='appt_calendar_app.account'),
        ),
    ]
