# Generated by Django 4.2.10 on 2024-05-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0035_alter_businessappearance_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_on', models.DateTimeField()),
                ('recipient', models.EmailField(max_length=240)),
                ('notes', models.CharField(max_length=500)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='appt_calendar_app.account')),
            ],
        ),
    ]
