# Generated by Django 4.2.10 on 2024-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0036_accountinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinvitation',
            old_name='recipient',
            new_name='recipient_email',
        ),
        migrations.AddField(
            model_name='accountinvitation',
            name='recipient_name',
            field=models.CharField(default='noemail@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
