# Generated by Django 4.2.10 on 2024-05-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0037_rename_recipient_accountinvitation_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvitation',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountinvitation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='appt_calendar_app.account'),
        ),
        migrations.AlterUniqueTogether(
            name='accountinvitation',
            unique_together={('business', 'recipient_email')},
        ),
    ]
