# Generated by Django 4.2.10 on 2024-05-07 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0038_alter_accountinvitation_accepted_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinvitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
