# Generated by Django 4.2.10 on 2024-05-09 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0039_accountinvitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinvitation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 10, 19, 9, 373337, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
