# Generated by Django 4.2.10 on 2024-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0040_accountinvitation_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventui',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
