# Generated by Django 4.2.10 on 2024-05-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0041_eventui_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='description',
            new_name='presentation',
        ),
    ]
