# Generated by Django 4.2.10 on 2024-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0042_rename_description_account_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventui',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
