# Generated by Django 4.2.10 on 2024-05-10 19:56

import appt_calendar_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0043_alter_eventui_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='appointment_background_image',
            field=models.ImageField(blank=True, default='appointment/placeholder.jpg', null=True, upload_to=appt_calendar_app.models.web_directory_path),
        ),
    ]
