# Generated by Django 4.2.10 on 2024-05-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0044_businessappearance_appointment_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessappearance',
            name='booking_form_background_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color for main form on the booking page', max_length=7),
        ),
    ]
