# Generated by Django 4.2.10 on 2024-05-12 16:49

import appt_calendar_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0045_businessappearance_booking_form_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=appt_calendar_app.models.user_uploads_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='appt_calendar_app.customuser')),
            ],
        ),
    ]
