# Generated by Django 4.2.10 on 2024-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0049_alter_appointmentcancellation_cancellation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentcancellation',
            name='cancelled_by',
            field=models.CharField(default='CLIENT', max_length=120),
            preserve_default=False,
        ),
    ]
