# Generated by Django 4.2.10 on 2024-05-16 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0051_appointmentcancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinvitation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
