# Generated by Django 4.2.10 on 2024-05-22 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0052_alter_accountinvitation_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-0.01)]),
        ),
    ]
