# Generated by Django 4.2.10 on 2024-05-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0053_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessappearance',
            name='background_color',
            field=models.CharField(default='#E8ECEB', help_text='Color of the website background.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='booking_form_background_color',
            field=models.CharField(default='#E8ECEB', help_text='Background color for main form on the booking page', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='buger_menu_lines_color',
            field=models.CharField(default='#E8ECEB', help_text='Burger menu line colors', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='burger_button_background_color',
            field=models.CharField(default='#E09E50', help_text='Background color for burger main menu', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='header_bar_color',
            field=models.CharField(default='#8CBDB9', help_text='Color of the header bar.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='header_bar_font_color',
            field=models.CharField(default='#000000', help_text='Font color for text on header bar.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='hero_image_font_color',
            field=models.CharField(default='#000000', help_text='Colors for text on main website image', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='main_manu_background_color',
            field=models.CharField(default='#8CBDB9', help_text='Background color for main menu', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='main_menu_font_color',
            field=models.CharField(default='#000000', help_text='Font color for main menu links', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='section_header_font_color',
            field=models.CharField(default='#000000', help_text='Color of the sections header text.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='service_background_color',
            field=models.CharField(default='#2D3E4E', help_text='Color of the service background card.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Color of the text on the website.', max_length=7),
        ),
        migrations.AlterField(
            model_name='businessappearance',
            name='worker_background_color',
            field=models.CharField(default='#E09E50', help_text='Color of the worker background card.', max_length=7),
        ),
    ]
