# Generated by Django 4.2.10 on 2024-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0054_alter_businessappearance_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='handler',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
