# Generated by Django 4.2.10 on 2024-05-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0057_alter_account_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='handler',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
