# Generated by Django 4.2.10 on 2024-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appt_calendar_app', '0059_event_handler_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='handler',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='handler',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
