services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=appointment_calendar.dev
    ports:
      - "8000:8000"
    command: ./wait-for-it.sh db:3306 -- python /code/manage.py runserver 0.0.0.0:8000

  nginx:
    ports:
      - "80:80"
